volumes:
  wardriving_postgres_db: {}
  redis_data: {}
  metabase_data: {}
  static_volume:
  media_volume:
  ctfd_logs:

services:
  wardrive:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    command: /code/start.sh
    env_file: .env
    depends_on:
      - wardrive_db
    stdin_open: true
    tty: true
    restart: on-failure
  wardrive_db:
    restart: on-failure
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - wardriving_postgres_db:/var/lib/postgresql/data:Z
  redis: # Define the Redis service
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672" # UI
    restart: on-failure

  ctfd_platform:
    build:
      context: ./ctfd
      dockerfile: Dockerfile
    volumes:
      - ctfd_logs:/opt/CTFd/logs
    environment:
      - REVERSE_PROXY=true
      - APPLICATION_ROOT=/ctf
      - DATABASE_URL=postgresql://postgres:postgres@wardrive_db:5432/ctfd
    depends_on:
      - wardrive_db
    restart: on-failure
  celery_proc_0:
    build: .
    command: /code/start_celery.sh
    environment:
      - QUEUE=proc_0
    volumes:
      - .:/code
    depends_on:
      - wardrive
      - redis
      - rabbitmq
    env_file: .env
    restart: on-failure

  celery_proc_1:
    build: .
    command: /code/start_celery.sh
    environment:
      - QUEUE=proc_1
    volumes:
      - .:/code
    depends_on:
      - wardrive
      - redis
      - rabbitmq
    env_file: .env
    restart: on-failure

  celery-beat:
    build: .
    command: /code/start_celery_beat.sh
    volumes:
      - .:/code
    depends_on:
      - wardrive
      - redis
    env_file: .env
    restart: on-failure
  wardrive_bi:
    image: metabase/metabase:v0.54.2
    env_file: .env
    volumes:
      - metabase_data:/metabase-data
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  wardrive_proxy:
    image: nginx:1.28.0
    depends_on:
      - wardrive
      - wardrive_bi
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
